openapi: 3.0.0
info:
  title: "QRAPI - Campaigns"
  version: 1.0.0
servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
paths:
  "/api/campaigns/manual":
    post:
      summary: "Create manual campaign"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "title": "Campa\u00f1a de prueba",
                  "groups": [
                    1,
                    2
                  ],
                  "message": "Hola, este es un mensaje de prueba.",
                  "schedule_at": "2025-10-01 10:00:00",
                  "attach_pdf": null
                }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Campa単a creada exitosamente",
                    "data": {
                      "id": 1,
                      "title": "Campa単a de prueba",
                      "groups": [1, 2],
                      "message": "Hola, este es un mensaje de prueba.",
                      "schedule_at": "2025-10-01 10:00:00",
                      "status": "scheduled"
                    }
                  }
  "/api/campaigns/list":
    get:
      summary: "Create excel campaign"
      parameters:
        - name: paginate
          in: query
          schema:
            type: integer
          description: Number of items per page
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "id": 1,
                        "title": "Campa単a de prueba",
                        "groups": [1, 2],
                        "message": "Hola, este es un mensaje de prueba.",
                        "schedule_at": "2025-10-01 10:00:00",
                        "status": "scheduled"
                      }
                    ],
                    "meta": {
                      "current_page": 1,
                      "per_page": 10,
                      "total": 1
                    }
                  }
  "/api/campaigns/show/{id}":
    get:
      summary: "Campaign Details"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Campaign ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": {
                      "id": 1,
                      "title": "Campa単a de prueba",
                      "groups": [1, 2],
                      "message": "Hola, este es un mensaje de prueba.",
                      "schedule_at": "2025-10-01 10:00:00",
                      "status": "scheduled",
                      "total_recipients": 50,
                      "sent": 45,
                      "failed": 5
                    }
                  }
