openapi: 3.0.0
info:
  title: "QRAPI - Campaigns"
  version: 1.0.0
servers:
  - url: https://{tenant_id}.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
  - url: https://qr.buho.la
    description: Main Server
paths:
  "/api/campaigns/manual":
    post:
      summary: "Create manual campaign"
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Success
  "/api/campaigns/list":
    get:
      summary: "Create excel campaign"
      responses:
        '200':
          description: Success
  "/api/campaigns/show/{id}":
    get:
      summary: "Campaign Details"
      responses:
        '200':
          description: Success
