openapi: 3.0.0
info:
  title: "Chat"
  version: 1.0.0
servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
paths:
  "/chat/numbers/check":
    post:
      summary: "Check is WhatsApp Number"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "numbers": [
                    "51955682576",
                    "5112345678"
                  ]
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "number": "51955682576",
                        "isWhatsApp": true
                      },
                      {
                        "number": "5112345678",
                        "isWhatsApp": false
                      }
                    ]
                  }
  "/chat/message/mark-read":
    post:
      summary: "Read Messages"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "readMessages": [
                    {
                      "remoteJid": "5112345678@s.whatsapp.net",
                      "fromMe": false,
                      "id": "AC7DADBF26C8FF9F768B2CF01A8EA581"
                    }
                  ]
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Mensajes marcados como leídos exitosamente"
                  }
  "/chat/archive":
    post:
      summary: "Archive Chat"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "chat": "51910398955@s.whatsapp.net",
                  "archive": true
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Chat archivado exitosamente",
                    "data": {
                      "chat": "51910398955@s.whatsapp.net",
                      "archive": true
                    }
                  }
  "/chat/message/mark-unread":
    post:
      summary: "Mark Chat Unread"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "lastMessage": {
                    "key": {
                      "remoteJid": "5112345678@s.whatsapp.net",
                      "fromMe": false,
                      "id": "AC7DADBF26C8FF9F768B2CF01A8EA581"
                    }
                  },
                  "chat": "51910398955@s.whatsapp.net"
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Chat marcado como no leído exitosamente"
                  }
  "/chat/message/delete":
    delete:
      summary: "Delete Message"
      parameters:
        - name: remoteJid
          in: query
          required: true
          schema:
            type: string
          description: Remote JID
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: Message ID
        - name: fromMe
          in: query
          schema:
            type: boolean
          description: Message from me
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Mensaje eliminado exitosamente"
                  }
  "/chat/contact/profile-picture":
    post:
      summary: "Fetch Profile Picture Copy"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "number": "51955682576@s.whatsapp.net"
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": {
                      "url": "https://mmg.whatsapp.net/...",
                      "mimetype": "image/jpeg"
                    }
                  }
  "/chat/message/base64":
    post:
      summary: "Get Base64 From Media Message Copy"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "key": {
                    "remoteJid": "123@s.whatsapp.net",
                    "fromMe": true,
                    "id": "3EB04DC69D97835D7CC6F12776D25766FBC224E2"
                  }
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": {
                      "base64": "iVBORw0KGgoAAAANSUhEUgAA...",
                      "mimetype": "image/jpeg"
                    }
                  }
  "/chat/message/update":
    post:
      summary: "Update Message"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "number": "{{remoteJid}}",
                  "key": {
                    "remoteJid": "123@s.whatsapp.net",
                    "fromMe": true,
                    "id": "3EB04DC69D97835D7CC6F12776D25766FBC224E2"
                  },
                  "text": "new message"
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Mensaje actualizado exitosamente",
                    "data": {
                      "key": {
                        "remoteJid": "123@s.whatsapp.net",
                        "fromMe": true,
                        "id": "3EB04DC69D97835D7CC6F12776D25766FBC224E2"
                      }
                    }
                  }
  "/chat/presence/send":
    post:
      summary: "Send Presence"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "number": "{{remoteJid}}",
                  "delay": 1200,
                  "presence": "composing"
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Presencia enviada exitosamente"
                  }
  "/message/contact/block":
    post:
      summary: "Update Block Status"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "number": "51955682576@s.whatsapp.net",
                  "block": true
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Estado de bloqueo actualizado exitosamente",
                    "data": {
                      "number": "51955682576@s.whatsapp.net",
                      "block": true
                    }
                  }
  "/chat/contact/find":
    post:
      summary: "Find Contacts"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "where": {
                    "name": "John"
                  }
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "id": "51955682576@s.whatsapp.net",
                        "name": "John Doe",
                        "notify": "John"
                      }
                    ]
                  }
  "/chat/message/find":
    post:
      summary: "Find Messages"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "where": {
                    "key": {
                      "remoteJid": "123@s.whatsapp.net"
                    }
                  }
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "key": {
                          "remoteJid": "123@s.whatsapp.net",
                          "fromMe": true,
                          "id": "3EB04DC69D97835D7CC6F12776D25766FBC224E2"
                        },
                        "message": {
                          "conversation": "Hello"
                        }
                      }
                    ]
                  }
  "/chat/status/find":
    post:
      summary: "Find Status Message"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "where": {}
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "key": {
                          "remoteJid": "status@broadcast",
                          "fromMe": false,
                          "id": "3EB04DC69D97835D7CC6F12776D25766FBC224E2"
                        },
                        "message": {
                          "extendedTextMessage": {
                            "text": "Status update"
                          }
                        }
                      }
                    ]
                  }
  "/chat/find":
    post:
      summary: "Find Chats"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "where": {
                    "unreadCount": {
                      ">": 0
                    }
                  }
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "id": "51910398955@s.whatsapp.net",
                        "unreadCount": 5,
                        "lastMessage": {
                          "key": {
                            "remoteJid": "51910398955@s.whatsapp.net",
                            "fromMe": false,
                            "id": "AC7DADBF26C8FF9F768B2CF01A8EA581"
                          }
                        }
                      }
                    ]
                  }
