openapi: 3.0.0
info:
  title: "QRAPI - Devices"
  version: 1.0.0
servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
  - url: https://qr.buho.la
    description: Main Server
paths:
  "/api/devices/create":
    post:
      summary: "Create Device"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "name": "Mi Dispositivo",
                  "phone": "51987654321"
                }
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Dispositivo creado exitosamente",
                    "data": {
                      "id": 1,
                      "name": "Mi Dispositivo",
                      "phone": "51987654321",
                      "status": "connected"
                    }
                  }
  "/api/devices/list":
    get:
      summary: "List Devices"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "id": 1,
                        "name": "Mi Dispositivo",
                        "phone": "51987654321",
                        "status": "connected"
                      }
                    ]
                  }
  "/api/devices/delete/{id}":
    delete:
      summary: "Delete Device"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Device ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Dispositivo eliminado exitosamente"
                  }
  "/api/devices/fetch":
    get:
      summary: "Fetch Device"
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          description: Device ID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": {
                      "id": 1,
                      "name": "Mi Dispositivo",
                      "phone": "51987654321",
                      "status": "connected",
                      "qrcode": "data:image/png;base64,..."
                    }
                  }