openapi: 3.0.0
info:
  title: "Label"
  version: 1.0.0
servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
  - url: https://qr.buho.la
    description: Main Server
paths:
  "/api/label/find":
    get:
      summary: "Find labels"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "data": [
                      {
                        "id": "1",
                        "name": "Important",
                        "color": "#FF5733"
                      }
                    ]
                  }
  "/api/label/handle":
    post:
      summary: "Handle Labels"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "number": "51936811821@s.whatsapp.net",
                  "labelId": "1",
                  "action": "add"
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Etiqueta aplicada exitosamente",
                    "data": {
                      "number": "51936811821@s.whatsapp.net",
                      "labelId": "1",
                      "action": "add"
                    }
                  }