openapi: 3.0.0
info:
  title: "Send Message"
  version: 1.0.0
servers:
  - url: https://{tenant_id}.qr.buho.la
    description: Tenant Server
    variables:
      tenant_id:
        default: demo
        description: Tenant Subdomain
  - url: https://qr.buho.la
    description: Main Server
paths:
  "/message/send":
    post:
      summary: "Button"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                {
                  "number": "51955682576",
                  "title": "Title Button",
                  "description": "Description Button",
                  "footer": "Footer Button",
                  "buttons": [
                    {
                      "type": "reply",
                      "displayText": "Resposta",
                      "id": "123"
                    }
                  ]
                }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                example:
                  {
                    "message": "Mensaje enviado exitosamente",
                    "data": {
                      "key": {
                        "remoteJid": "51955682576@s.whatsapp.net",
                        "fromMe": true,
                        "id": "3EB0FDF1AB6CAE81793069"
                      },
                      "status": "PENDING"
                    }
                  }